- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL server
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download MongoDB schema files
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Load schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
