- name: Copy MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MYSQL-python
    state: installed

- name: Start MySQL service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes



- name: Handle the error
  block:
    - name: Get MySQL version to check the DB connection
      mysql_info:
        login_user: root
        login_password: "{{MYSQL_PASSWORD}}"
        filter: version
  rescue:
    - name: Load MySQL log file
      ansible.builtin.slurp:
          src: /var/log/mysqld.log
      register: mysql_log

    - name: Declare facts
      ansible.builtin.set_fact:
        DEFAULT_PASS: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') | split(' ') | last}}"

    - name: Change MySQL
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASSWORD}}';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASS}}"

- name: Check Validate plugin exists or not
  ansible.builtin.shell: echo "uninstall plugin validate_password" | mysql -uroot -p{{MYSQL_PASSWORD}}
  ignore_errors: yes

- name: Download MySQL schema files
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"

