- name: Setup the NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Roboshop App user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Application user


- name: Remove old App content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Download catalogue content & extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Copy catalogue content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /usr/roboshop/catalogue
    remote_src: yes
    become_user: roboshop

- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Copy catalogue SystemD file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Restart catalogue
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon-reload: yes

