
- name: Add Roboshop App user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Application user

- name: Remove old App content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Download {{COMPONENT}} content & extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Copy {{COMPONENT}} content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /usr/roboshop/{{COMPONENT}}
    remote_src: yes
    become_user: roboshop

